# https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: nearest
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false

ignore:
  - "examples"
  - "third_party"
  - "tests"
