[[nodes]]
    name = "h0"
    type = "model"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.1/30"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.0.2"
[[nodes]]
    name = "h1"
    type = "model"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.1.1/30"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "8.8.8.1/24"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.1.2"
[[nodes]]
    name = "h2"
    type = "model"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.2.1/30"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "8.8.8.2/24"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.2.2"
[[nodes]]
    name = "r0"
    type = "model"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.2/30"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "192.168.1.2/30"
    [[nodes.interfaces]]
    name = "eth2"
    ipv4 = "192.168.2.2/30"
[[nodes]]
    name = "s1"
    type = "model"
    [[nodes.interfaces]]
    name = "eth0"
    [[nodes.interfaces]]
    name = "eth1"
    [[nodes.interfaces]]
    name = "eth2"
[[nodes]]
    name = "server"
    type = "model"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "8.8.8.8/24"
[[links]]
    node1 = "h0"
    intf1 = "eth0"
    node2 = "r0"
    intf2 = "eth0"
[[links]]
    node1 = "h1"
    intf1 = "eth0"
    node2 = "r0"
    intf2 = "eth1"
[[links]]
    node1 = "h2"
    intf1 = "eth0"
    node2 = "r0"
    intf2 = "eth2"
[[links]]
    node1 = "h1"
    intf1 = "eth1"
    node2 = "s1"
    intf2 = "eth1"
[[links]]
    node1 = "h2"
    intf1 = "eth1"
    node2 = "s1"
    intf2 = "eth2"
[[links]]
    node1 = "server"
    intf1 = "eth0"
    node2 = "s1"
    intf2 = "eth0"

[openflow]
    [[openflow.updates]]
    node = "r0"
    network = "8.8.8.0/24"
    outport = "eth1"
    [[openflow.updates]]
    node = "r0"
    network = "8.8.8.8/32"
    outport = "eth2"

[[invariants]]
    type = "waypoint"
    target_node = "h1"
    pass_through = false
    [[invariants.connections]]
    protocol = "tcp"
    src_node = "h0"
    dst_ip = "8.8.8.8"
    dst_port = [80]
[[invariants]]
    type = "waypoint"
    target_node = "h2"
    pass_through = true
    [[invariants.connections]]
    protocol = "tcp"
    src_node = "h0"
    dst_ip = "8.8.8.8"
    dst_port = [80]
