##
## Network configuration
##

[[nodes]]
    name = "<string>"
    type = "<string>"           # "model" or "emulation"
    [[nodes.interfaces]]        # optional
    name = "<string>"
    ipv4 = "<ip addr/mask>"     # optional
    vlans = [1, 3, 6, 100]      # optional (not supported yet)
    [[nodes.static_routes]]     # optional
    network = "<ip prefix>"
    next_hop = "<ip addr>"
    adm_dist = 1                # optional (1..254), default: 1
    [[nodes.installed_routes]]  # optional
    network = "<ip prefix>"
    next_hop = "<ip addr>"
    adm_dist = 254              # optional (1..254), default: 255
[[nodes]]
    name = "<string>"
    type = "emulation"
    driver = "docker"           # optional ("docker"), default: "docker"
    # Optional, socket endpoint of the docker daemon.
    # For a remote service, use something like "http://10.0.0.1:33444".
    # Default: "/var/run/docker.sock"
    docker-daemon = "/var/run/docker.sock"
    [nodes.container]
    # https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container
    image = "alpine:3.17"
    workingDir = "/"
    command = ["/bin/sh"]       # optional
    args = []                   # optional
    config_files = []           # optional
    [[nodes.container.ports]]   # optional
    containerPort = 1234
    protocol = "tcp"            # "tcp" or "udp"
    [[nodes.container.env]]     # optional
    name = "PATH"
    value = "/usr/sbin/:/usr/bin:/sbin:/bin"
    [[nodes.container.volumeMounts]]    # optional
    mountPath = ""
    hostPath = ""
    driver = "local"            # optional ("local"), default: "local"
    readOnly = false            # optional, default: false
    [[nodes.container.sysctls]] # optional
    key = ""
    value = ""

# undirected (only need to specify once for each link)
[[links]]
    node1 = "<name>"
    intf1 = "<name>"
    node2 = "<name>"
    intf2 = "<name>"


##
## OpenFlow configuration
##

[openflow]
    [[openflow.updates]]
    node = "<name>"
    network = "<ip prefix>"
    outport = "<egress interface name>"


##
## Policies
##

#
# Single-connection policies (must have 1 connection spec):
#   - reachability (flow will reach the target(s))
#   - reply-reachability (<reachability> and reply flow will come back)
#   - waypoint (flow will pass through the target(s) (don't have to be accepted))
#
[[policies]]
    type = "reachability"
    target_node = "<node name regex>"
    reachable = true
    [[policies.connections]]        # < connection spec >
    protocol = "<string>"           # "tcp", "udp", or "icmp-echo"
    src_node = "<node name regex>"
    dst_ip = "<ip prefix or addr>"
    src_port = 12345                # optional
    dst_port = [80, 443]            # optional, default: all interesting ports
    owned_dst_only = false          # optional, default: false
[[policies]]
    type = "reply-reachability"
    target_node = "<node name regex>"
    reachable = true
    [[policies.connections]]
    # < connection spec >
[[policies]]
    type = "waypoint"
    target_node = "<node name regex>"
    pass_through = true
    [[policies.connections]]
    # < connection spec >

#
# Multi-connection policies (can have multiple, concurrent connection specs):
#   - one-request (only one request will reach the target(s))
#   - loadbalance (the dispersion index wrt the targets will always <= the maximum)
#
[[policies]]
    type = "one-request"
    target_node = "<node name regex>"
    [[policies.connections]]
    # < connection spec >
[[policies]]
    type = "loadbalance"
    target_node = "node name regex"
    max_dispersion_index = 1        # optional, default: 1
    [[policies.connections]]
    # < connection spec >

#
# Policies with multiple correlated sub-policies
# (each sub-policy is executed sequentially):
#   - conditional (chain of implication: A -> B -> C -> ...)
#   - consistency (true if all sub-policies have the same result)
#
[[policies]]
    type = "conditional"
    [[policies.correlated_policies]]
    # < any single-connection policy >
[[policies]]
    type = "consistency"
    [[policies.correlated_policies]]
    # < any single-connection policy >
