name: test
on: [push, pull_request]
jobs:

  style-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install clang-format yapf3
      - run: ./test/style.sh

  build:
    needs: style-check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cc: [gcc, clang]
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: ./depends/setup.sh
      - run: >
          cmake -B build -S .
          -DCMAKE_BUILD_TYPE=Debug
          -DENABLE_TESTS=ON
          -DENABLE_COVERAGE=ON
          -DCMAKE_C_COMPILER=${{ matrix.cc }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
      - run: cmake --build build
#      - run: ctest
#        working-directory: ./build
#      - uses: codecov/codecov-action@v1
#        with:
#          fail_ci_if_error: true
#          gcov_args: '-l'
#        if: matrix.cc == 'gcc'
