name: test
on: [push, pull_request]
jobs:

  style-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install clang-format yapf3
      - run: ./test/style.sh

  tests:
    needs: style-check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cc: [gcc, clang]
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: ./depends/setup.sh
      - run: ./test/build.sh --debug --tests --coverage --${{ matrix.cc }}
      - run: ctest --progress --output-on-failure
        working-directory: ./build
      - uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_args: '-l'
        if: matrix.cc == 'gcc'
