name: test
on: [push, pull_request]
jobs:

  tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cc: [gcc, clang]
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: ./depends/setup.sh
      - run: ./scripts/style.sh
      - run: ./scripts/configure.sh -d -t --${{ matrix.cc }}
      - run: ./scripts/build.sh
      - run: ./scripts/test.sh
