name: test
on: [push, pull_request]
jobs:

  # style-check:
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: sudo apt install clang-format yapf3
  #     - run: ./scripts/style.sh

  tests:
    needs: style-check
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cc: [gcc, clang]
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: ./depends/setup.sh
      - run: ./scripts/configure.sh -d -t --${{ matrix.cc }}
      - run: ./scripts/build.sh
      - run: ./scripts/test.sh
      # - if: matrix.cc == 'gcc'
      #   uses: codecov/codecov-action@v3
      #   with:
      #     gcov: true
      #     gcov_args: '-l'
